name: Busted
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Run Busted
        uses: lunarmodules/busted@v2.2.0
        with:
          args: test
        env:
          LUA_PATH: "./?.lua;./lib/?.lua;./lib/?/?.lua;./lib/comiclib/lib/?.lua;./lib/comiclib/third_party/?/?.lua"
